### ISSUE TITLE
Implementar métodos que modificam o background do canvas

### ISSUE THREAD

**Issue by guiaugusto** [ThalissonMelo/turtle#6]
**Descrição**

Para ser semelhante ao proposto pela biblioteca que estamos usando de base (turtle do python), é necessario implementar os métodos relacionados as mudanças no background de cada canvas instanciado (sendo um comando especifico por canvas/screen).

**Tasks**

- [x] Validar todos os principais métodos utilizados pelo Turtle python para fazer essa associação.
- [x] Implementar métodos

**Comment by guiaugusto** [comment]
Os métodos validados e implementados foram:

- [x] forward
- [x] backward
- [x] setLineColor
- [x] speed
- [x] commandList (para executar multiplos comandos)
- [x] right (para mudar a angulação para o lado direito no sentido da turtle)
- [x] left (para mudar a angulação para o lado esquerdo no sentido da turtle)
- [x] setPosition
- [x] penUp
- [x] penDown
- [x] angle
