### ISSUE TITLE
Implementar possibilidade de atrelar mais de uma turtle a apenas um canvas

### ISSUE THREAD

**Issue by guiaugusto** [ThalissonMelo/turtle#7]
**Descrição**

Para ser semelhante ao proposto pela biblioteca que estamos usando de base (turtle do python), é necessario possibilitar a existência de diversas turtles em apenas um componente, conseguindo executar comandos para apenas uma turtle e realizando alterações gerais nos desenhos feitos por cada turtle, conseguindo remover, adicionar ou modificar uma turtle em específico

**Tasks**

- [x] Permitir a criação de uma ou várias turtles em um canvas
- [x] Permitir a remoção de uma ou várias turtles de um canvas
- [x] Permitir a execução de comandos específicos para cada turtle

**Comment by guiaugusto** [comment]
A forma de desenvolvimento da criação de uma turtle é feita na criação de um canvas "invisível" que acompanha a animação do sprite, e outro canvas que recebe os comandos para desenho.

É possível, atualmente, apenas a criação e execução de comandos para cada turtle.
